!! Reads the main namnelist and adds variables to global data module
subroutine read_namelist()
  use mc_data_mod
  implicit none

  integer :: nml_iostat
  character(len=512) :: nml_iomsg

  open(newunit=u_nml, file='CMCRT.nml', status='old', action='read', &
    & iostat=nml_iostat, iomsg=nml_iomsg)
  if (nml_iostat /= 0) then
    print*, 'ERROR opening CMCRT.nml: ', trim(nml_iomsg)
    stop
  end if

  read(u_nml, nml=main, iostat=nml_iostat, iomsg=nml_iomsg)
  if (nml_iostat /= 0) then
    print*, 'ERROR reading &main from CMCRT.nml: ', trim(nml_iomsg)
    stop
  end if

  if (random_seed < 0) then
    print*, 'ERROR: random_seed must be non-negative.'
    stop
  end if
  random_seed_d = random_seed
  print*, 'Random seed: ', random_seed

  if (n_phase < 1) then
    print*, 'ERROR: n_phase must be positive.'
    stop
  end if

  if (oneD .eqv. threeD) then
    print*, 'ERROR: exactly one of oneD or threeD must be true.'
    stop
  end if

  if (ck .eqv. lbl) then
    print*, 'ERROR: exactly one of ck or lbl must be true.'
    stop
  end if

  if (inc_ck .and. .not. ck) then
    print*, 'ERROR: inc_ck requires ck = .True.'
    stop
  end if

  if (inc_lbl .and. .not. lbl) then
    print*, 'ERROR: inc_lbl requires lbl = .True.'
    stop
  end if

  if (inc_ck .and. inc_lbl) then
    print*, 'ERROR: inc_ck and inc_lbl cannot both be true.'
    stop
  end if

  if (ecc /= 0.0_dp) then
    print*, 'ERROR: non-zero orbital eccentricity is not supported; set ecc = 0.'
    stop
  end if

  if (doppler_on .eqv. .True.) then
    select case(trim(xper))
    case('3D_sph_em_hi', '3D_sph_trans_hi')
      continue
    case default
      print*, 'ERROR: Doppler shifting is supported only by high-resolution modes.'
      print*, 'Use 3D_sph_em_hi or 3D_sph_trans_hi, or set doppler_on = .False.'
      stop
    end select
  end if

  if (wght_deg .eqv. .True.) then
    print*, 'ERROR: wght_deg is disabled because it applies absorption twice.'
    stop
  end if

  if (do_BB_band .eqv. .True.) then
    print*, 'ERROR: do_BB_band is not implemented; use monochromatic emission.'
    stop
  end if

  if (do_surf .eqv. .True.) then
    print*, 'ERROR: surface emission/reflection is not implemented in active 3D modes.'
    stop
  end if

  if ((trim(xper) == '3D_sph_alb') .and. (do_LD .eqv. .True.)) then
    print*, 'ERROR: transit limb darkening is not a valid albedo illumination model.'
    stop
  end if

  if ((trim(xper) == '3D_sph_alb') .and. (do_scat_loop .eqv. .False.)) then
    print*, 'ERROR: 3D_sph_alb requires do_scat_loop = .True.'
    print*, 'Reflected light is generated by the scattering loop.'
    stop
  end if

  if (do_LD .eqv. .True.) then
    if ((ilimb < 1) .or. (ilimb > 8)) then
      print*, 'ERROR: ilimb must be between 1 and 8 when do_LD is true.'
      print*, 'ilimb: ', ilimb
      stop
    end if

    if ((ilimb == 5) .and. (LD_c(2) /= 0.0_dp)) then
      print*, 'ERROR: exponential limb darkening is singular at mu=0 when LD_c(2) is nonzero.'
      print*, 'LD_c(2): ', LD_c(2)
      stop
    end if
  end if

  select case(trim(xper))
  case('3D_sph_trans', '3D_sph_trans_hi')
    do_trans_spectrum = .True.
  case default
    ! Transit light curves use source_pac_inc_3D_transit and their own
    ! phase-dependent disk/lens normalization.
    do_trans_spectrum = .False.
  end select

  ! Send some flags to the device
  do_images_d = do_images ! images switch
  do_moments_d = do_moments ! calculate J, H, K moments
  do_trans_spectrum_d = do_trans_spectrum
  do_cf_d = do_cf ! For contribution functions
  inc_refrac_d = inc_refrac

  do_scat_loop_d = do_scat_loop

  ! Transport schemes may opt into per-block accumulators after their
  ! experiment-specific namelist is read.  Keep all schemes on the legacy
  ! scalar path until that selection is made.
  use_block_accum_d = .False.

  do_g_bias_d = do_g_bias

  wght_deg_d = wght_deg ! Include weight degradiation

  do_LD_d = do_LD
  ilimb_d = ilimb
  LD_c_d(:) = LD_c(:)
  Rs_d = Rs
  inc_d = inc
  sm_ax_d = sm_ax

  do_eclipse_d = do_eclipse
  do_phase_d = do_phase

  orbital_period_d = orbital_period 

  do_surf_d = do_surf
  alb_surf_d = alb_surf

  LHS_d = LHS

end subroutine read_namelist


subroutine read_CMCRT_par()
  use mc_data_mod
  implicit none

  integer :: u_par

  open(newunit=u_par, file='CMCRT.par', status='old', action='read')



end subroutine read_CMCRT_par
